### ISSUE TITLE
[BUG] - On click of Allow push notifications fails

### ISSUE THREAD

**Issue by smaldd14** [jevonmao/PermissionsSwiftUI#74] opened 2021-05-27 02:26 UTC
Hi, I've set up my iOS app to ask for permissions like so:
            .JMModal(showModal: self.$showModal, for: [.locationAlways, .notification])
Allowing location successfully changes button to allowed, but allowing push notifications does not change the button to allowed, therefore, I cannot exit the modal.

However, I do see printouts in my appDelegate's  didRegisterForRemoteNotificationsWithDeviceToken: saying that I have successfully registered? Everytime I click allow I see the button. I only see the Apple alert for allowing push notifications the very first time. But, button does not change to allowed.

**To Reproduce**
1. Show JMModal with .locationAlways and .notification
2. Allow Notifications
3. See error

push notifications should change button to allowed and be able to dismiss.

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 1.4

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro device

**Additional context**

**Comment by smaldd14** [comment] 2021-05-27 02:27
By the way, I am absolutely loving this package and its ease of use! I am really am enjoying this, just wondering why notifications does not work??

**Comment by smaldd14** [comment] 2021-05-27 02:35
Also, as I'm testing more, I'm seeing if I stop the app from running AFTER I allow all notifications the first time, and then start the app again; when I get to the point when JMModal should show, it will not show (I'm assuming because all notifications have been allowed and JMModal recognizes that)

**Comment by macteuts** [comment] 2021-05-28 14:44
Same here. Allowing notifications does nothing any longer. No more screen update. Though I also believe the notifications have actually been allowed (didn't check yet).
Also the "close" button doesn't closes.

**Comment by jevonmao** [comment] 2021-05-28 18:49
@macteuts @smaldd14 Thank you very much for the bug report. I will look into the issue and try to reproduce it first. In the meantime, you might want to set `restrictDismissal` to false so it doesn't prevent user from dismissing the modal.

**Comment by jevonmao** [comment] 2021-05-29 19:07
@macteuts @smaldd14 The bug is confirmed, and after looking into it for a while, I cannot figure out the reason this is happening. I will continue to try to fix this, but if you are not using any 1.4.0 API, you should for now re-add the package 1.3.0 version which works perfectly and does not have this bug.

**Comment by gharary** [comment] 2021-06-07 08:27
Same here. Allowing notifications do nothing any longer.
Using 1.4.2 version.

**Comment by smaldd14** [comment] 2021-06-09 00:09
Any updates on this bug??

**Comment by jevonmao** [comment] 2021-06-09 00:30
@smaldd14 WWDC 2021 just announced the new `async/await` feature which will be very useful to resolving this bug. ETA 2-3 more days needed to fix and new version will be released. Thank you everyone for understanding.

**Comment by jevonmao** [comment] 2021-06-09 03:46
@macteuts @gharary @smaldd14 @fnazarios 

Everyone, please try newest 1.4.3 version and see if it's fixed.

**Comment by smaldd14** [comment] 2021-06-09 22:52
@jevonmao in version 1.4.3, the notifications button successfully turns to 'Allowed', but the auto dismissal still does not happen.is this something you're aware of?

**Comment by jevonmao** [comment] 2021-06-12 23:56
Closing for now because this is fixed and no further activity.

**Closed by jevonmao** 2021-06-12 23:56 UTC
Labels: confirmed bug, help wanted
